="<STYLE>a.icctt:hover {text-decoration:none;}"
	&"a.icctt span {z-index:10;display:none;width:200px;padding:5px;margin:20 0 0 -340;text-align:left;}"
	&"a.icctt:hover span{display:inline;position:absolute;color:#111;border:1px solid #DCA;background:#fffAF0;}"
	&".callout {z-index:20;position:absolute;top:130px;border:0;left:-120px;}"
&"</STYLE>"

&"<img src='/_layouts/images/blank.gif' onload=""{"
	&"function ICCmyTR(me){while(me.tagName!='TR'){me=me.parentNode}return(me)}"
	&"function ICCmyTD(me){while(me.parentNode.tagName!='TR'){me=me.parentNode}return(me)}"
	&"function ICChide(me){me.style.display='none'}"
	&"function ICChideheader(TRnode,n){ICChide(TRnode.parentNode.parentNode.firstChild.firstChild.children[n])}"
	&"function ICCcolNR(me){TR=ICCmyTR(me);myTD=ICCmyTD(me);for(i=0;i<TR.children.length;i++){if(myTD==TR.children[i]){break;}}return(i)}"
	&"function ICCcontentNode(me){while(me.firstChild!=null){me=me.firstChild}return(me.parentNode)}"
	&"function ICCprevTD(me){return(ICCmyTD(me).previousSibling)}"
	&"function ICCshort(me){P=me.firstChild;if(!P)return;"
		&"if(P.className=='ms-rtestate-field'){S=(ICCcontentNode(P).innerHTML);"
		&"if(S.length>1){P.innerHTML='<A HREF=# class=icctt>'+S.substring(0,15)+'...<span>'+P.innerHTML+'</span></a>';}}}"
	&"function ICCshortenAll(me){TD=ICCmyTR(me).firstChild;do{ICCshort(TD);TD=TD.nextSibling;}while(TD)}"

	&"ICCshortenAll(this);"
&"}"">"
