="<input type='text' value='"
&MONTH([Created])&"/"
&DAY([Created])&"/"
&YEAR([Created])&"'/>"
&"<button onclick='javascript:{"
&"  var TRnode,tDate,clientContext,list,item,created,newDate;"
&"  TRnode=this.parentNode.parentNode.parentNode;"
&"	tDate=this.previousSibling;"
&"	if(tDate.nextSibling.innerHTML==""Reload""){window.location.reload()};"
&"	clientContext=new SP.ClientContext.get_current();"
&"	list=clientContext.get_web().get_lists().getById(SP.ListOperation.Selection.getSelectedList());"
&"	item=list.getItemById( TRnode.iid.split("","")[1] );"
&"	clientContext.load(item);"
&"	clientContext.executeQueryAsync(function(){"
&"		created=item.get_item(""Created"");"
&"		newDate=tDate.value.split(""/"");"
&"		created.setMonth   (newDate[0]-1);"
&"		created.setDate    (newDate[1]);"
&"		created.setFullYear(newDate[2]);"
&"		item.set_item(""Created"",created);"
&"		item.update();"
&"		tDate.style.backgroundColor=""LimeGreen"";"
&"		tDate.nextSibling.innerHTML=""Reload"";"
&"  })}'>Touch</button>"