="<img src='/_layouts/images/blank.gif' onload=""{"
&"var Selected='"&[Prioriteit]&"';"
&"var Options=['(1) Hoog','(2) Standaard','(3) Laag'];"
&"var Colors=['none','lightpink','bisque','cornsilk'];"
&"if('"&[Taakstatus]&"'==='Niet gestart'){"
	&"this.parentNode.parentNode.parentNode.style.backgroundColor=Colors[Selected.match(/(\d+)/g)];"
&"}"
&"var select = document.createElement('SELECT');"
&"select.onchange=function(){"
	&"var MYnode, clientContext, itemid, list, item;"
	&"MYnode=this.parentNode.parentNode;"
	&"MYnode.parentNode.style.backgroundColor=Colors[this.value.match(/(\d+)/g)];"
	&"itemid=MYnode.parentNode.getAttribute( 'iid' ).split(',')[1];"
	&"clientContext=new SP.ClientContext.get_current();"
	&"list=clientContext.get_web().get_lists().getById(SP.ListOperation.Selection.getSelectedList());"
	&"item=list.getItemById(itemid);"
	&"item.set_item('Priority',this.value);"
	&"item.update();"
	&"clientContext.executeQueryAsync("
		&"(function(){MYnode.style.border='thin dotted red'}) ,"
		&"(function(){alert('failed ICC function')})"
	&")"
&"};"
&"for(i=0;i<Options.length;i++){"
	&"var option = document.createElement('OPTION');"
	&"option.selected = (Options[i]===Selected);"
	&"option.value = Options[i];"
	&"option.text = Options[i];"
	&"select.appendChild(option);"
&"}"
&"this.parentNode.appendChild(select,this);"
&"}"">"
